<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Regenerasi logo SVG inline + partial Blade dari PNG sumber.
 *
 * Pipeline: downscale mask alpha (ambang 64) -> marching squares boundary
 * walk (solid di kanan arah jalan, prioritas belok kanan-lurus-kiri) ->
 * simplifikasi RDP (eps 1.0 @ 400px tinggi) -> path digabung evenodd ->
 * tulis public/logo*.svg + resources/views/layouts/_logo-*.blade.php.
 *
 * Pemakaian: php artisan logo:regenerate
 * (jalankan setelah mengganti public/logo.png / public/logo-square.png)
 */
class LogoRegenerate extends Command
{
    protected $signature = 'logo:regenerate
                            {--height=400 : Tinggi rasterisasi mask (px)}';

    protected $description = 'Regenerasi logo SVG inline + partial Blade dari public/logo*.png';

    public function handle(): int
    {
        $height = max(120, (int) $this->option('height'));
        $eps = 1.0;

        $jobs = [
            ['public/logo.png', 'public/logo.svg',
                'resources/views/layouts/_logo-long.blade.php', 48, 'IF Language School'],
            ['public/logo-square.png', 'public/logo-square.svg',
                'resources/views/layouts/_logo-square.blade.php', 56, 'IF Language School'],
        ];

        foreach ($jobs as [$png, $svg, $partial, $displayHeight, $label]) {
            if (! is_file($png)) {
                $this->warn("Lewati: $png tidak ada");

                continue;
            }

            [$mask, $W, $H] = $this->buildMask($png, $height);
            $contours = $this->traceContours($mask, $W, $H);

            if ($contours === []) {
                $this->error("Tidak ada kontur terdeteksi di $png — cek alpha channel-nya");

                return self::FAILURE;
            }

            $d = implode(' ', array_map(
                fn (array $c) => $this->contourToPath($this->simplifyRDP($c, $eps)),
                $contours
            ));

            file_put_contents($svg, sprintf(
                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" fill="currentColor" fill-rule="evenodd" aria-hidden="true"><path d="%s"/></svg>',
                $W, $H, $d
            ));

            $blade = "{{-- Generated by 'php artisan logo:regenerate' — jangan edit manual.\n"
                ."     Logo inline SVG: fill ikut warna teks (currentColor), tajam semua resolusi,\n"
                ."     transparan sempurna tanpa risiko background PNG (lihat commit cc19cd0). --}}\n"
                ."@php\n"
                ."\$d = '".str_replace("'", "\\'", $d)."';\n"
                ."\$vb = '0 0 $W $H';\n"
                ."@endphp\n"
                .'<svg viewBox="{{ $vb }}" height="'.$displayHeight.'" style="width:auto;display:inline-block;vertical-align:middle;" role="img" aria-label="'.$label.'" fill="currentColor" fill-rule="evenodd"><path d="{{ $d }}"/></svg>'."\n";
            file_put_contents($partial, $blade);

            $this->info(basename($png).' → '.basename($svg).": ".count($contours)." kontur, "
                .round(strlen($d) / 1024, 1)." KB path, {$W}x{$H}");
        }

        $this->newLine();
        $this->components->info('Partial diperbarui: _logo-long.blade.php & _logo-square.blade.php — jalankan view:clear bila perlu.');

        return self::SUCCESS;
    }

    // ---------- Mask ----------

    /** Downscale PNG + ambang alpha menjadi mask boolean. */
    private function buildMask(string $file, int $targetH): array
    {
        $src = imagecreatefrompng($file);
        $sw = imagesx($src);
        $sh = imagesy($src);
        $scale = $targetH / $sh;
        $tw = (int) round($sw * $scale);
        $small = imagecreatetruecolor($tw, $targetH);
        imagealphablending($small, false);
        imagesavealpha($small, true);
        imagecopyresampled($small, $src, 0, 0, 0, 0, $tw, $targetH, $sw, $sh);

        $mask = [];
        for ($y = 0; $y < $targetH; $y++) {
            $row = [];
            for ($x = 0; $x < $tw; $x++) {
                $c = imagecolorsforindex($small, imagecolorat($small, $x, $y));
                // Ambang 64: piksel setengah tertutup dihitung solid (anti-alias ikut bentuk)
                $row[] = $c['alpha'] < 64;
            }
            $mask[] = $row;
        }

        return [$mask, $tw, $targetH];
    }

    // ---------- Marching squares ----------

    /** Telusuri semua kontur (outer + lubang) pada grid sudut. */
    private function traceContours(array $mask, int $W, int $H): array
    {
        $PW = $W + 2;
        $PH = $H + 2;
        // Pad 1 piksel kosong agar kontur tertutup di tepi gambar
        $P = array_fill(0, $PH, array_fill(0, $PW, false));
        for ($y = 0; $y < $H; $y++) {
            for ($x = 0; $x < $W; $x++) {
                $P[$y + 1][$x + 1] = $mask[$y][$x];
            }
        }

        $solid = fn (int $x, int $y): bool => $x >= 0 && $y >= 0 && $x < $PW && $y < $PH && $P[$y][$x];
        $visited = [];
        $contours = [];

        // Titik awal: tepi atas piksel solid yang di atasnya kosong
        for ($sy = 0; $sy < $PH; $sy++) {
            for ($sx = 0; $sx < $PW; $sx++) {
                if (isset($visited["$sx,$sy"])) {
                    continue;
                }
                if ($solid($sx, $sy) && ! $solid($sx, $sy - 1)) {
                    $c = $this->walkContour($solid, $sx, $sy, $visited);
                    if (count($c) >= 4) {
                        $contours[] = $c;
                    }
                }
            }
        }

        return $contours;
    }

    /** Jalan mengikuti antarmuka solid/kosong; solid selalu di kanan arah jalan. */
    private function walkContour(callable $solid, int $startX, int $startY, array &$visited): array
    {
        $dirs = [[1, 0], [0, 1], [-1, 0], [0, -1]]; // kanan, bawah, kiri, atas
        $x = $startX;
        $y = $startY;
        $dir = 0;
        $pts = [];
        $steps = 0;

        do {
            $pts[] = [$x, $y];
            $visited["$x,$y"] = true;

            // Prioritas belok: kanan, lurus, kiri — validitas diuji pada
            // SEGMENT yang berangkat dari sudut saat ini (bukan tujuan).
            $found = false;
            foreach ([1, 0, 3] as $turn) {
                $nd = ($dir + $turn) % 4;
                [$dx, $dy] = $dirs[$nd];
                if ($this->isBoundaryEdge($solid, $x, $y, $nd)) {
                    $x += $dx;
                    $y += $dy;
                    $dir = $nd;
                    $found = true;
                    break;
                }
            }
            if (! $found) {
                break;
            }
        } while (($x !== $startX || $y !== $startY) && ++$steps < 500000);

        return $pts;
    }

    /** Apakah langkah dari sudut C=(x,y) arah d menyusuri antarmuka solid/kosong? */
    private function isBoundaryEdge(callable $solid, int $x, int $y, int $d): bool
    {
        return match ($d) {
            0 => $solid($x, $y) && ! $solid($x, $y - 1),         // → solid di bawah tepi
            1 => $solid($x - 1, $y) && ! $solid($x, $y),         // ↓ solid di kiri tepi
            2 => $solid($x - 1, $y - 1) && ! $solid($x - 1, $y), // ← solid di atas tepi
            3 => $solid($x, $y - 1) && ! $solid($x - 1, $y - 1), // ↑ solid di kanan tepi
            default => false,
        };
    }

    // ---------- Simplifikasi & path ----------

    /** Ramer–Douglas–Peucker. */
    private function simplifyRDP(array $pts, float $eps): array
    {
        $n = count($pts);
        if ($n < 3) {
            return $pts;
        }
        $keep = array_fill(0, $n, false);
        $keep[0] = $keep[$n - 1] = true;
        $stack = [[0, $n - 1]];
        while ($stack) {
            [$a, $b] = array_pop($stack);
            if ($b <= $a + 1) {
                continue;
            }
            $ax = $pts[$a][0];
            $ay = $pts[$a][1];
            $bx = $pts[$b][0];
            $by = $pts[$b][1];
            $dx = $bx - $ax;
            $dy = $by - $ay;
            $len = sqrt($dx * $dx + $dy * $dy) ?: 1;
            $maxD = 0.0;
            $maxI = -1;
            for ($i = $a + 1; $i < $b; $i++) {
                $d = abs($dy * $pts[$i][0] - $dx * $pts[$i][1] + $bx * $ay - $by * $ax) / $len;
                if ($d > $maxD) {
                    $maxD = $d;
                    $maxI = $i;
                }
            }
            if ($maxD > $eps) {
                $keep[$maxI] = true;
                $stack[] = [$a, $maxI];
                $stack[] = [$maxI, $b];
            }
        }

        return array_values(array_filter($pts, fn ($_, $i) => $keep[$i], ARRAY_FILTER_USE_BOTH));
    }

    private function contourToPath(array $contour): string
    {
        $d = '';
        foreach ($contour as $i => [$x, $y]) {
            $d .= ($i === 0 ? 'M' : 'L').$x.' '.$y;
        }

        return $d.'Z';
    }
}
